Repository ConvergenceSwAce/22-F-ML-Project, pull requests merged in 2022-10, with the labels that each got.

#15 사람 인식 기능 추가, 조건식 변경, 모델 개선, 예외처리
  cross+person.py
Labels: enhancement

#18 Chore : 파일 정리, ignore 변경
  .gitignore
  bot.py
  cross+person.py
  cross.py
  models/yolov4-ANPR.cfg
Labels: documentation

#22 Feat : 객체 개수 인식 및 경고 라벨 추가
  cross.py
Labels: enhancement

#23 Feat : 실시간 비디오 객체 인식
  cross.py
Labels: enhancement

#24 Feat : TTS 추가
  cross.py
Labels: enhancement

#26 Chore : playsound 삭제, 실시간 비디오 캡쳐
  cross.py
Labels: enhancement

#27 Feat : text파일 쓰기, Chore : 필요없는 변수 제거, 주석 추가
  cross.py
  notification.txt
  sample.mp3
  warn.txt
Labels: enhancement

#29 Feat : BE 완료
  app.py
  model/readFile.py
  requirements.txt
Labels: enhancement

#30 Refactor : TTS 삭제, Docs : README 수정
  Beyond Sight.jpg
  README.md
  requirements.txt
  sample.txt
  text_to_speech.py
Labels: documentation

#32 Chore : TTS import 제거
  cross.py
Labels: bug
